name = "smart-wallets-data"

[[tables]]
name = "signers"

[[tables.columns]]
name = "address"
col_type = "BYTEA"

[[tables.columns]]
name = "id"
col_type = "BYTEA"

[[tables.columns]]
name = "pubkey"
col_type = "BYTEA"

[[tables.columns]]
name = "active"
col_type = "BYTEA"


[[tables]]
name = "adjacent"

[[tables.columns]]
name = "contract"
col_type = "BYTEA"

[[tables.columns]]
name = "topics"
col_type = "BYTEA"

[[tables.columns]]
name = "data"
col_type = "BYTEA"

[[tables.columns]]
name = "address"
col_type = "BYTEA"
